In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"C:\Users\micha\OneDrive\Documents\PRSGWAS_tsv\GCST90104545_buildGRCh37EA.tsv\Meta_IS_BothMandF_GIGA_ASN_allfiles_metaAnalyseSEbased_wogc_2021June11_NeNs3rdDp1e6.gwascatalog.tsv_2"
gwas_EAdata = pd.read_csv(path, sep='\t')
display(gwas_EAdata)

,chromosome,base_pair_location,effect_allele_frequency,beta,standard_error,p_value,odds_ratio,ci_lower,ci_upper,effect_allele,other_allele
0,5,29439275,0.7798,0.0106,0.0136,0.4351,1.010656,0.984072,1.037959,T,C
1,5,85928892,0.0221,0.0484,0.0395,0.2202,1.049590,0.971397,1.134078,T,C
2,10,128341232,0.4628,0.0106,0.0115,0.3547,1.010656,0.988131,1.033695,T,C
3,3,62707519,0.0689,0.0029,0.0226,0.8983,1.002904,0.959449,1.048327,T,C
4,2,80464120,0.9098,0.0294,0.0196,0.1334,1.029836,0.991025,1.070168,T,G
...,...,...,...,...,...,...,...,...,...,...,...
6725211,7,118234612,0.4058,0.0014,0.0114,0.9053,1.001401,0.979274,1.024028,A,G
6725212,10,25609933,0.0133,-0.0526,0.0599,0.3806,0.948759,0.843661,1.066950,A,C
6725213,18,44156714,0.2241,0.0064,0.0140,0.6454,1.006421,0.979180,1.034419,C,G
6725214,18,56346817,0.0166,-0.0184,0.0486,0.7049,0.981768,0.892565,1.079887,A,G
6725215,11,99622387,0.3111,0.0107,0.0123,0.3835,1.010757,0.986681,1.035421,T,C

In [3]:
rename_dict = {
    'chromosome': 'CHR',
    'base_pair_location': 'BP',
    'effect_allele': 'A1',      # A1 is the target/risk allele
    'other_allele': 'A2',       # A2 is the baseline allele
    'beta': 'BETA',
    'p_value': 'P',
    'effect_allele_frequency': 'EAF',
    'standard_error': 'SE',
    'odds_ratio': 'OR'
}

In [4]:
earename = gwas_EAdata.rename(columns=rename_dict)

In [5]:
earename

,CHR,BP,EAF,BETA,SE,P,OR,ci_lower,ci_upper,A1,A2
0,5,29439275,0.7798,0.0106,0.0136,0.4351,1.010656,0.984072,1.037959,T,C
1,5,85928892,0.0221,0.0484,0.0395,0.2202,1.049590,0.971397,1.134078,T,C
2,10,128341232,0.4628,0.0106,0.0115,0.3547,1.010656,0.988131,1.033695,T,C
3,3,62707519,0.0689,0.0029,0.0226,0.8983,1.002904,0.959449,1.048327,T,C
4,2,80464120,0.9098,0.0294,0.0196,0.1334,1.029836,0.991025,1.070168,T,G
...,...,...,...,...,...,...,...,...,...,...,...
6725211,7,118234612,0.4058,0.0014,0.0114,0.9053,1.001401,0.979274,1.024028,A,G
6725212,10,25609933,0.0133,-0.0526,0.0599,0.3806,0.948759,0.843661,1.066950,A,C
6725213,18,44156714,0.2241,0.0064,0.0140,0.6454,1.006421,0.979180,1.034419,C,G
6725214,18,56346817,0.0166,-0.0184,0.0486,0.7049,0.981768,0.892565,1.079887,A,G
6725215,11,99622387,0.3111,0.0107,0.0123,0.3835,1.010757,0.986681,1.035421,T,C

In [6]:
columns_to_keep = ['CHR', 'BP', 'A1', 'A2', 'BETA', 'P', 'EAF', 'SE', 'OR'] 
ea = earename[columns_to_keep]
ea

         CHR         BP A1 A2    BETA       P     EAF      SE        OR
0          5   29439275  T  C  0.0106  0.4351  0.7798  0.0136  1.010656
1          5   85928892  T  C  0.0484  0.2202  0.0221  0.0395  1.049590
2         10  128341232  T  C  0.0106  0.3547  0.4628  0.0115  1.010656
3          3   62707519  T  C  0.0029  0.8983  0.0689  0.0226  1.002904
4          2   80464120  T  G  0.0294  0.1334  0.9098  0.0196  1.029836
...      ...        ... .. ..     ...     ...     ...     ...       ...
6725211    7  118234612  A  G  0.0014  0.9053  0.4058  0.0114  1.001401
6725212   10   25609933  A  C -0.0526  0.3806  0.0133  0.0599  0.948759
6725213   18   44156714  C  G  0.0064  0.6454  0.2241  0.0140  1.006421
6725214   18   56346817  A  G -0.0184  0.7049  0.0166  0.0486  0.981768
6725215   11   99622387  T  C  0.0107  0.3835  0.3111  0.0123  1.010757

[6725216 rows x 9 columns]

In [7]:
missing = ea.isna().sum()
print(missing)

CHR     0
BP      0
A1      0
A2      0
BETA    0
P       0
EAF     0
SE      0
OR      0
dtype: int64

In [8]:
ea['MAF'] = np.where(
    ea['EAF'] > 0.5,     # The IF condition because Minor Alleles need to be less than 0.5, if effect allele is less than 0.5, calculation does not apply and MAF = EAF
    1 - ea['EAF'],       # What to do if TRUE
    ea['EAF']            # What to do if FALSE
)

C:\Users\micha\AppData\Local\Temp\ipykernel_17396\4036628138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ea['MAF'] = np.where(

In [9]:
ea

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0106,0.4351,0.7798,0.0136,1.010656,0.2202
1,5,85928892,T,C,0.0484,0.2202,0.0221,0.0395,1.049590,0.0221
2,10,128341232,T,C,0.0106,0.3547,0.4628,0.0115,1.010656,0.4628
3,3,62707519,T,C,0.0029,0.8983,0.0689,0.0226,1.002904,0.0689
4,2,80464120,T,G,0.0294,0.1334,0.9098,0.0196,1.029836,0.0902
...,...,...,...,...,...,...,...,...,...,...
6725211,7,118234612,A,G,0.0014,0.9053,0.4058,0.0114,1.001401,0.4058
6725212,10,25609933,A,C,-0.0526,0.3806,0.0133,0.0599,0.948759,0.0133
6725213,18,44156714,C,G,0.0064,0.6454,0.2241,0.0140,1.006421,0.2241
6725214,18,56346817,A,G,-0.0184,0.7049,0.0166,0.0486,0.981768,0.0166
6725215,11,99622387,T,C,0.0107,0.3835,0.3111,0.0123,1.010757,0.3111

In [10]:
# Find the lowest and highest EAF in your data, for sanity check if calculations were wrong
min_eaf = ea['EAF'].min() 
max_eaf = ea['EAF'].max()

print(f"The lowest EAF is: {min_eaf}")
print(f"The highest EAF is: {max_eaf}")

The lowest EAF is: 0.0101
The highest EAF is: 0.9899

In [11]:
ea = ea[ea['MAF'] >= 0.01] # Filtering SNPs with MAF less than 1%, theory is this may be only noise

In [12]:
ea

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0106,0.4351,0.7798,0.0136,1.010656,0.2202
1,5,85928892,T,C,0.0484,0.2202,0.0221,0.0395,1.049590,0.0221
2,10,128341232,T,C,0.0106,0.3547,0.4628,0.0115,1.010656,0.4628
3,3,62707519,T,C,0.0029,0.8983,0.0689,0.0226,1.002904,0.0689
4,2,80464120,T,G,0.0294,0.1334,0.9098,0.0196,1.029836,0.0902
...,...,...,...,...,...,...,...,...,...,...
6725211,7,118234612,A,G,0.0014,0.9053,0.4058,0.0114,1.001401,0.4058
6725212,10,25609933,A,C,-0.0526,0.3806,0.0133,0.0599,0.948759,0.0133
6725213,18,44156714,C,G,0.0064,0.6454,0.2241,0.0140,1.006421,0.2241
6725214,18,56346817,A,G,-0.0184,0.7049,0.0166,0.0486,0.981768,0.0166
6725215,11,99622387,T,C,0.0107,0.3835,0.3111,0.0123,1.010757,0.3111

In [13]:
# Check for duplicate SNPs
print(ea.duplicated(subset=['CHR', 'BP']).sum())

0

In [14]:
ea = ea[(ea['P'] > 0) & (ea['P'] <= 1)]

In [15]:
ea

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0106,0.4351,0.7798,0.0136,1.010656,0.2202
1,5,85928892,T,C,0.0484,0.2202,0.0221,0.0395,1.049590,0.0221
2,10,128341232,T,C,0.0106,0.3547,0.4628,0.0115,1.010656,0.4628
3,3,62707519,T,C,0.0029,0.8983,0.0689,0.0226,1.002904,0.0689
4,2,80464120,T,G,0.0294,0.1334,0.9098,0.0196,1.029836,0.0902
...,...,...,...,...,...,...,...,...,...,...
6725211,7,118234612,A,G,0.0014,0.9053,0.4058,0.0114,1.001401,0.4058
6725212,10,25609933,A,C,-0.0526,0.3806,0.0133,0.0599,0.948759,0.0133
6725213,18,44156714,C,G,0.0064,0.6454,0.2241,0.0140,1.006421,0.2241
6725214,18,56346817,A,G,-0.0184,0.7049,0.0166,0.0486,0.981768,0.0166
6725215,11,99622387,T,C,0.0107,0.3835,0.3111,0.0123,1.010757,0.3111

In [16]:
ea.to_csv('EA_Data_Gigastroke_Cleaned.txt', sep='\t', index=False)