In [1]:
import pandas as pd
import numpy as np

In [2]:
path1 = r"C:\Users\micha\OneDrive\Documents\PRSGWAS_tsv\GCST90104535_buildGRCh37TRANS.tsv\Meta_IS_BothMandF_GIGA_TRANS_allfiles_metaAnalyseSEbased_wogc_2021June11_NeNs3rdDp1e6.gwascatalog.tsv_2"
gwas_TRANSdata = pd.read_csv(path1, sep='\t')
display(gwas_TRANSdata)

,chromosome,base_pair_location,effect_allele_frequency,beta,standard_error,p_value,odds_ratio,ci_lower,ci_upper,effect_allele,other_allele
0,5,85928892,0.0673,-0.0104,0.0135,0.44120,0.989654,0.963811,1.016190,T,C
1,10,128341232,0.4638,0.0072,0.0060,0.23140,1.007226,0.995450,1.019141,T,C
2,18,51112281,0.7023,0.0092,0.0067,0.16780,1.009242,0.996076,1.022583,T,C
3,4,55643311,0.2232,0.0050,0.0073,0.49360,1.005013,0.990735,1.019496,T,C
4,1,4429872,0.0764,0.0037,0.0121,0.76030,1.003707,0.980183,1.027795,T,G
...,...,...,...,...,...,...,...,...,...,...,...
7407878,7,118234612,0.5061,-0.0028,0.0058,0.62800,0.997204,0.985932,1.008605,A,G
7407879,7,125463763,0.0346,-0.0347,0.0248,0.16200,0.965895,0.920068,1.014005,T,G
7407880,3,80436770,0.9576,-0.0482,0.0188,0.01021,0.952943,0.918468,0.988712,A,G
7407881,18,44156714,0.2020,0.0048,0.0075,0.52540,1.004812,0.990149,1.019691,C,G
7407882,4,104138439,0.0264,0.0344,0.0255,0.17780,1.034999,0.984541,1.088042,A,G

In [ ]:
# Renaming Columns and drop unnecessary columns

In [3]:
rename_dict = {
    'chromosome': 'CHR',
    'base_pair_location': 'BP',
    'effect_allele': 'A1',      # A1 is the target/risk allele
    'other_allele': 'A2',       # A2 is the baseline allele
    'beta': 'BETA',
    'p_value': 'P',
    'effect_allele_frequency': 'EAF',
    'standard_error': 'SE',
    'odds_ratio': 'OR'
}

In [4]:
transrename = gwas_TRANSdata.rename(columns=rename_dict)

In [5]:
transrename

,CHR,BP,EAF,BETA,SE,P,OR,ci_lower,ci_upper,A1,A2
0,5,85928892,0.0673,-0.0104,0.0135,0.44120,0.989654,0.963811,1.016190,T,C
1,10,128341232,0.4638,0.0072,0.0060,0.23140,1.007226,0.995450,1.019141,T,C
2,18,51112281,0.7023,0.0092,0.0067,0.16780,1.009242,0.996076,1.022583,T,C
3,4,55643311,0.2232,0.0050,0.0073,0.49360,1.005013,0.990735,1.019496,T,C
4,1,4429872,0.0764,0.0037,0.0121,0.76030,1.003707,0.980183,1.027795,T,G
...,...,...,...,...,...,...,...,...,...,...,...
7407878,7,118234612,0.5061,-0.0028,0.0058,0.62800,0.997204,0.985932,1.008605,A,G
7407879,7,125463763,0.0346,-0.0347,0.0248,0.16200,0.965895,0.920068,1.014005,T,G
7407880,3,80436770,0.9576,-0.0482,0.0188,0.01021,0.952943,0.918468,0.988712,A,G
7407881,18,44156714,0.2020,0.0048,0.0075,0.52540,1.004812,0.990149,1.019691,C,G
7407882,4,104138439,0.0264,0.0344,0.0255,0.17780,1.034999,0.984541,1.088042,A,G

In [6]:
columns_to_keep = ['CHR', 'BP', 'A1', 'A2', 'BETA', 'P', 'EAF', 'SE', 'OR'] # odd ratio and standard error

In [7]:
trans = transrename[columns_to_keep]

In [8]:
trans

         CHR         BP A1 A2    BETA        P     EAF      SE        OR
0          5   85928892  T  C -0.0104  0.44120  0.0673  0.0135  0.989654
1         10  128341232  T  C  0.0072  0.23140  0.4638  0.0060  1.007226
2         18   51112281  T  C  0.0092  0.16780  0.7023  0.0067  1.009242
3          4   55643311  T  C  0.0050  0.49360  0.2232  0.0073  1.005013
4          1    4429872  T  G  0.0037  0.76030  0.0764  0.0121  1.003707
...      ...        ... .. ..     ...      ...     ...     ...       ...
7407878    7  118234612  A  G -0.0028  0.62800  0.5061  0.0058  0.997204
7407879    7  125463763  T  G -0.0347  0.16200  0.0346  0.0248  0.965895
7407880    3   80436770  A  G -0.0482  0.01021  0.9576  0.0188  0.952943
7407881   18   44156714  C  G  0.0048  0.52540  0.2020  0.0075  1.004812
7407882    4  104138439  A  G  0.0344  0.17780  0.0264  0.0255  1.034999

[7407883 rows x 9 columns]

In [ ]:
# Check and remove NaN Values

In [9]:
missing = trans.isna().sum()
print(missing)

CHR     0
BP      0
A1      0
A2      0
BETA    0
P       0
EAF     0
SE      0
OR      0
dtype: int64

In [ ]:
# Removing ambiguous SNPs, *ralat krn gaperlu diremove, sebenernya perlu sih krn ambigu klo forward strandnya A/T trs reversenya T/A

In [32]:
#is_AT = ((transrename['A1'] == 'A') & (transrename['A2'] == 'T')) | \
#        ((transrename['A1'] == 'T') & (transrename['A2'] == 'A'))

#is_CG = ((transrename['A1'] == 'C') & (transrename['A2'] == 'G')) | \
#        ((transrename['A1'] == 'G') & (transrename['A2'] == 'C'))

#is_ambiguous = is_AT | is_CG
#gwas_clean = trans[~is_ambiguous].copy()

In [33]:
#num_ambiguous = is_ambiguous.sum()
#total_snps = len(trans)
#percentage = (num_ambiguous / total_snps) * 100

#print(f"Total SNPs in dataset: {total_snps}")
#print(f"Total ambiguous SNPs found: {num_ambiguous}")
#print(f"Percentage to be removed: {percentage:.2f}%\n")

Total SNPs in dataset: 7407883
Total ambiguous SNPs found: 1128044
Percentage to be removed: 15.23%

In [34]:
#ambiguous_snps_df = trans[is_ambiguous]

#display(ambiguous_snps_df.head())

    CHR         BP A1 A2    BETA        P     EAF
7     3  192574024  C  G -0.0020  0.74300  0.4582
9    16   77819425  C  G  0.0116  0.31180  0.8960
14   18   73604213  A  T -0.0037  0.53980  0.4096
22    6   27649763  C  G  0.0160  0.05567  0.1818
38    3  129333182  C  G -0.0069  0.54360  0.9018

In [35]:
#trans_clean = trans[~is_ambiguous].copy()

In [36]:
#original_count = len(trans)
#clean_count = len(trans_clean)
#removed_count = original_count - clean_count

#print(f"Original SNP count: {original_count}")
#print(f"Clean SNP count:    {clean_count}")
#print(f"Successfully deleted {removed_count} palindromic SNPs from the pipeline.")

Original SNP count: 7407883
Clean SNP count:    6279839
Successfully deleted 1128044 palindromic SNPs from the pipeline.

In [10]:
trans

         CHR         BP A1 A2    BETA        P     EAF      SE        OR
0          5   85928892  T  C -0.0104  0.44120  0.0673  0.0135  0.989654
1         10  128341232  T  C  0.0072  0.23140  0.4638  0.0060  1.007226
2         18   51112281  T  C  0.0092  0.16780  0.7023  0.0067  1.009242
3          4   55643311  T  C  0.0050  0.49360  0.2232  0.0073  1.005013
4          1    4429872  T  G  0.0037  0.76030  0.0764  0.0121  1.003707
...      ...        ... .. ..     ...      ...     ...     ...       ...
7407878    7  118234612  A  G -0.0028  0.62800  0.5061  0.0058  0.997204
7407879    7  125463763  T  G -0.0347  0.16200  0.0346  0.0248  0.965895
7407880    3   80436770  A  G -0.0482  0.01021  0.9576  0.0188  0.952943
7407881   18   44156714  C  G  0.0048  0.52540  0.2020  0.0075  1.004812
7407882    4  104138439  A  G  0.0344  0.17780  0.0264  0.0255  1.034999

[7407883 rows x 9 columns]

In [38]:
#trans_clean

         CHR         BP A1 A2    BETA        P     EAF
0          5   85928892  T  C -0.0104  0.44120  0.0673
1         10  128341232  T  C  0.0072  0.23140  0.4638
2         18   51112281  T  C  0.0092  0.16780  0.7023
3          4   55643311  T  C  0.0050  0.49360  0.2232
4          1    4429872  T  G  0.0037  0.76030  0.0764
...      ...        ... .. ..     ...      ...     ...
7407877    4  113306346  A  C  0.0159  0.40900  0.0534
7407878    7  118234612  A  G -0.0028  0.62800  0.5061
7407879    7  125463763  T  G -0.0347  0.16200  0.0346
7407880    3   80436770  A  G -0.0482  0.01021  0.9576
7407882    4  104138439  A  G  0.0344  0.17780  0.0264

[6279839 rows x 7 columns]

In [ ]:
# MAF calculation and cutoff using EAF number, >=1%, can be more lenient to the cutoff due to less reference for indonesian dataset

In [21]:
trans['MAF'] = np.where(
    trans['EAF'] > 0.5,     # The IF condition because Minor Alleles need to be less than 0.5, if effect allele is less than 0.5, calculation does not apply and MAF = EAF
    1 - trans['EAF'],       # What to do if TRUE
    trans['EAF']            # What to do if FALSE
)

NameError: name 'ea' is not defined

In [12]:
trans

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,85928892,T,C,-0.0104,0.44120,0.0673,0.0135,0.989654,0.0673
1,10,128341232,T,C,0.0072,0.23140,0.4638,0.0060,1.007226,0.4638
2,18,51112281,T,C,0.0092,0.16780,0.7023,0.0067,1.009242,0.2977
3,4,55643311,T,C,0.0050,0.49360,0.2232,0.0073,1.005013,0.2232
4,1,4429872,T,G,0.0037,0.76030,0.0764,0.0121,1.003707,0.0764
...,...,...,...,...,...,...,...,...,...,...
7407878,7,118234612,A,G,-0.0028,0.62800,0.5061,0.0058,0.997204,0.4939
7407879,7,125463763,T,G,-0.0347,0.16200,0.0346,0.0248,0.965895,0.0346
7407880,3,80436770,A,G,-0.0482,0.01021,0.9576,0.0188,0.952943,0.0424
7407881,18,44156714,C,G,0.0048,0.52540,0.2020,0.0075,1.004812,0.2020
7407882,4,104138439,A,G,0.0344,0.17780,0.0264,0.0255,1.034999,0.0264

In [13]:
trans = trans[trans['MAF'] >= 0.01] # Filtering SNPs with MAF less than 1%, theory is this may be only noise

In [14]:
# Find the lowest and highest EAF in your data, for sanity check if calculations were wrong
min_eaf = trans['EAF'].min() 
max_eaf = trans['EAF'].max()

print(f"The lowest EAF is: {min_eaf}")
print(f"The highest EAF is: {max_eaf}")

The lowest EAF is: 0.0115
The highest EAF is: 0.9886

In [15]:
# Check for duplicate SNPs
print(trans.duplicated(subset=['CHR', 'BP']).sum())

0

In [16]:
# P value cutoff where the P-value is greater than 0 and less than or equal to 1, can be more lenient to the cutoff due to less reference for indonesian dataset
trans = trans[(trans['P'] > 0) & (trans['P'] <= 1)]

In [17]:
trans

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,85928892,T,C,-0.0104,0.44120,0.0673,0.0135,0.989654,0.0673
1,10,128341232,T,C,0.0072,0.23140,0.4638,0.0060,1.007226,0.4638
2,18,51112281,T,C,0.0092,0.16780,0.7023,0.0067,1.009242,0.2977
3,4,55643311,T,C,0.0050,0.49360,0.2232,0.0073,1.005013,0.2232
4,1,4429872,T,G,0.0037,0.76030,0.0764,0.0121,1.003707,0.0764
...,...,...,...,...,...,...,...,...,...,...
7407878,7,118234612,A,G,-0.0028,0.62800,0.5061,0.0058,0.997204,0.4939
7407879,7,125463763,T,G,-0.0347,0.16200,0.0346,0.0248,0.965895,0.0346
7407880,3,80436770,A,G,-0.0482,0.01021,0.9576,0.0188,0.952943,0.0424
7407881,18,44156714,C,G,0.0048,0.52540,0.2020,0.0075,1.004812,0.2020
7407882,4,104138439,A,G,0.0344,0.17780,0.0264,0.0255,1.034999,0.0264

In [19]:
trans.to_csv('Trans_Data_Gigastroke_Cleaned.txt', sep='\t', index=False)

In [20]:
import os
print(os.getcwd())

C:\Users\micha